### ISSUE TITLE
What to do with the Native MongoDB stuff?

### ISSUE THREAD

**Issue by WilliamChan4** [WilliamChan4/SENG2021_TheFastGroup#100]
There are currently 4 branches #79 #86 #91 #99 related to the native MongoDB stuff that @william-coulter wrote. They haven't been committed to master, principally because the code in master from #52 was faulty and thus the authors of the branches were not able to successfully complete the enhancements they were supposed to achieve. 

I suggest merging them all into a single branch (not master), then try to find out what we can salvage from them. 

I also suggest attaching the issues they were supposed to resolve to the pull requests to reduce our issue backlog!

**Comment by soroushMosaddad99** [comment]
that would probably be a good idea, but lets see what @william-coulter thinks about this.

**Comment by WilliamChan4** [comment]
I've changed the existing pull requests to merge into "features/NativeMongoDBStuff"

**Comment by WilliamChan4** [comment]
Sure. @william-coulter what do you think?

**Comment by WilliamChan4** [comment]
Not relevant anymore. Switching to typegoose.
