### ISSUE TITLE
[APP BAR]: Reduce text

### ISSUE THREAD

**Issue by william-coulter** [WilliamChan4/SENG2021_TheFastGroup#166]
Right now the app bar reads:

 "ICON Logged in as NAME - Points: POINTS LOGOUTBUTTON"

let's reduce the text in this so that it's just

"ICON Welcome, NAME 1 POINT (OR POINTS) LOGOUTBUTTON"

Maybe reduce text further if the logout button still jumps to a new line.

**Comment by WilliamChan4** [comment]
It would be better if the previous alignment to the far left and right remained. But it is fine for now.
