### ISSUE TITLE
Part 2: Identify and Describe User Stories

### ISSUE THREAD

**Issue by lkihuynh** [WilliamChan4/SENG2021_TheFastGroup#3]
### BASIC TEMPLATES FOR USER STORIES
- Requirement

- Feature

- Description of the Feature + Description of a potential Scenario

- "**As a** student, **I want to** search tutors by their reputation scores **so that** I can find a qualified tutor"

- GIVEN, WHEN, THEN, WHEN, THEN, AND

**Comment by WilliamChan4** [comment]
The user stories are in the deliverable 1 Google Drive document and published in the /deliverables folder.
