### ISSUE TITLE
Part 3: Low-Fidelity Prototype

### ISSUE THREAD

**Issue by R-Tramsport** [WilliamChan4/SENG2021_TheFastGroup#4]
Subtasks:
- Storyboard interactions Graphs
- UI Component Sketches
- Storyboard interactions + UI Components Sketches

**Comment by WilliamChan4** [comment]
The low fidelity prototypes are in the Deliverable 1 Google Drive doc and in the Deliverable 1 PDF in the /deliverables folder.
