### ISSUE TITLE
ENDPOINT: api/challenges/get-by-id

### ISSUE THREAD

**Issue by william-coulter** [WilliamChan4/SENG2021_TheFastGroup#57]
Method: GET
QueryParams: id (primary key of Challenge)
Body: none
Response: Challenge Object

**Comment by william-coulter** [comment]
/******************************************************************************
 *   Get Challenge by id - "GET /api/challenges/by-id"
 ******************************************************************************/

router.get("/by-id", async (req: Request, res: Response) => {
    try {
        // challengeService.getChallengesForUser(req.params["user"]);
        const challenge: Challenge = challengeService.getChallengeById(
            req.params["id"]
        );

        return res.send({ challenge: challenge });
    } catch (err) {
        logger.error(err.message, err);
        return res.status(BAD_REQUEST).json({
            error: err.message
        });
    }
});

**Comment by Tina-A-Zhang** [comment]
in challenges.ts file there's only route get_by_user and get_all, am I working on get_all or get_by_id?

**Comment by WilliamChan4** [comment]
Does the endpoint in your branch work now?

**Comment by Tina-A-Zhang** [comment]
Hi William, I think I've done the coding part, haven't tested yet. do just I create some dummy data and use postman for testing?

**Comment by WilliamChan4** [comment]
Yes. You can create some dummy data and use postman for testing.

How did you do the coding without having something to test it against
though?

Even though we don't currently have any automated tests (yikes!) and are
not currently doing TDD, we should be manually testing our code against all
foreseeable test cases to make sure it works after every small change. :)

**Comment by Tina-A-Zhang** [comment]
sure. ah I asked Will before because I didn't know where to start. he listed a few things I need do. so I just followed that. I'll start doing testing tonight!

**Comment by WilliamChan4** [comment]
Great!

There are some issues with the current API design that I'll raise at the
next meeting when we do the sequence diagrams (e.g. users are currently
able to arbitrarily increase the points they have by calling the
/add-points endpoint!). That shouldn't affect the work you're doing though.
:)
