### ISSUE TITLE
[Should] Create a refresh challenge user story?

### ISSUE THREAD

**Issue by WilliamChan4** [WilliamChan4/SENG2021_TheFastGroup#93]
Instead of being able to refresh each of the definitions individually, I think it would be easier to refresh all of the definitions together (create a new draft challenge altogether).

**Comment by WilliamChan4** [comment]
@soroushMosaddad99

**Comment by WilliamChan4** [comment]
This could be achieved by a single Refresh button and a call to the GET challenges/draft route

**Comment by WilliamChan4** [comment]
@soroushMosaddad99 This isn't a crucial deliverable. But if you want to do something extra, you could always give this a try 😉

**Comment by soroushMosaddad99** [comment]
thanks William

**Comment by WilliamChan4** [comment]
@soroushMosaddad99 Sorry, but we probably won't have time to do this.
