### ISSUE TITLE
[Should] List draft and completed challenges on the home screen?

### ISSUE THREAD

**Issue by WilliamChan4** [WilliamChan4/SENG2021_TheFastGroup#94]
Since it is possible for users to create multiple draft challenges without ever submitting them, they should be presented on the home screen so that they can either complete them or delete them. We should also consider whether draft challenges should be on a different table, or be on the same table as all other challenges with some null fields.

**Comment by WilliamChan4** [comment]
We could also list completed challenges on the user's home screen (but this would take up more database space in the long run).

**Comment by WilliamChan4** [comment]
Since we now have a concept of "draft" challenges, this creates a subclassing of the challenge entity in our ER diagram. One way of handling this would be using a discriminator. Using Typegoose (a TypeScript way of using Mongoose), this is relatively easy to achieve (but our documentation will need to be updated to reflect this). 

https://typegoose.github.io/typegoose/docs/functions/getDiscriminatorModelForClass/

**Comment by soroushMosaddad99** [comment]
In that case, will the users be able to review the completed challenges?
this would be similar to what @R-Tramsport mentioned during the first deliverable.

**Comment by WilliamChan4** [comment]
Yes.

**Comment by WilliamChan4** [comment]
This probably won't happen.
