### ISSUE TITLE
Will the native MongoDB requests cause issues with Mongoose?

### ISSUE THREAD

**Issue by WilliamChan4** [WilliamChan4/SENG2021_TheFastGroup#96]
It appears Mongoose makes a single connection to the database with which is streams all requests. The way the native MongoDB stuff in this repository at the moment is structured (making a new connection per request) may lead to race conditions and conflicts with Mongoose.

**Comment by william-coulter** [comment]
Yeah good question but I don't think so.

Mongoose will just open up a new connection to the database.

**Comment by soroushMosaddad99** [comment]
not so sure about this one, we need further examination.

**Comment by WilliamChan4** [comment]
At the moment, I'm thinking of converting the existing database stuff to Typegoose.
