### ISSUE TITLE
What to do about the Deliverable 3 Demo branches?

### ISSUE THREAD

**Issue by WilliamChan4** [WilliamChan4/SENG2021_TheFastGroup#98]
I was thinking of combining the Demo branches for Deliverable 3, merging the Deliverable 3 PowerPoint pull request, then creating a release which you can access from "Releases" on the repository homepage or via the tag v3.0 (as with the tag v1.0 for Deliverable 1). 

What does everyone think?

**Comment by WilliamChan4** [comment]
There seem to be some useful changes in those branches such as adding the Password field to the login page (though the id's will need to be unique etc. but that's stuff we can sort out in a pull request review).

**Comment by soroushMosaddad99** [comment]
that sounds like a reasonable thing to do.
